version: "3"
services:
  khanto-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py loaddata property.json && python manage.py loaddata advertisement.json && python manage.py loaddata booking.json && python manage.py runserver 0.0.0.0:8000 "
    ports:
      - 8000:8000
    volumes:
      - .:/app
