# Generated by Django 5.0.3 on 2024-03-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_guests', models.SmallIntegerField()),
                ('bathroom_count', models.SmallIntegerField()),
                ('accept_pets', models.BooleanField()),
                ('cleaning_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activation_date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
